pipeline {
    agent any
    stages {
        stage("clean up"){
            steps {
                deleteDir()
            }
        }
        stage("clone repo"){
            steps {
                sh "git clone https://github.com/aayushrcdac/gtest_cmake.git"
            }
        }
        stage("build"){
            steps {
                dir("gtest_cmake") {
                    sh " conan install . --output-folder=build --build=missing"
                }
                dir("gtest_cmake/build") {
                    sh "cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/aayushr/.jenkins/workspace/conan_proj/gtest_cmake/build/build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release"
                    sh "make"
                }
            }
        }
        stage("test the app"){
            steps {
                
                dir("gtest_cmake/build") {
                    sh "./main"
                }   
                
            }
        }
    }

}
